
//! MATERI TENTANG GRADLE 

//! 1. APA ITU BUILD OTOMATION
//? BUILD OTOMATION ADALAH SEBUAH PROSES MENG-OTOMATISASI TAHAPAN PEMBUATAN SOFTWARE DAN HAL-HAL YG BERHUBUNGAN DENGANNYA,
//TODO:CONTOHNYA SEPRETI 
/* 
  - KOMPILASI ATAU MENGUBAH SOURCE CODE MENJADI BINARY CODE, 
  - MEM-PACKAGE BINARY CODE MENJADI DISTRIBUTION FILE, 
  - MEMBUAT DOKUMENTASI 
  - MENJALANKAN AUTOMATED TEST
  - MANAJEMEN ATAU MENGATUR DEPENDENCY
*/
//TOOD: PROSES COMPILE CODE JADI BINARY FILE ( SOURCE CODE -> COMPILE -> BINARY FILE (1101101))
//TOOD: PROSES MEM-PACKAGE BINARY FILE ( BINARY FILE (1101101) -> PACKAGING -> DISTRIBUTION FILE )

//! 2. APA ITU GRADLE 
//? GRADLE ADALAH SALAH SATU BUILD AUTOMATION TOOL OPEN SOURCE YG BISA DIGUNAKAN ANDROID,JAVA DAN KOTLIN
//TODO: GRADLE MENGGUNAKAN BAHASA GROOVY ATAU KOTLIN UNTUK MENDEFINISIKAN ATAU MEMBUAT KONFIGURASI BUILD SCRIPTNYA  
//TODO: GRADLE POPULER DI GUNAKAN OLEH DEVELOPER ANDROID DAN MENGGUNAKAN JVM SEBAGAI FONDASI DASARNYA
/*  
  YANG BISA DI LAKUKAN GRADLE 

  - Compile source code
  - Download dependency
  - Generate APK/AAB
  - Menjalankan task build

*/

//! 3. APA ITU GROOVY
//? GROOVY ADALAH SALAH SATU BAHASA PEMOGRAMAN YG DIGUNAKAN UNTUK MENDEFINISIKAN ATAU MEMBUAT KONFIGURASI BUILD SCRIPTNYA 
//todo: cmn unutk tahun 2018 atau versi gradle Gradle 5.0 rekomendasi bahasa yg di pake adalah kotlin dsl
