
//! MATERI TENTANG GRADLE 

//! 1. APA ITU BUILD OTOMATION
//? BUILD OTOMATION ADALAH PROSES MENG-OTOMATISASI TAHAPAN PEMBUATAN SOFTWARE DAN HAL-HAL YG BERHUBUNGAN DENGANNYA,
//TODO:CONTOHNYA SEPRETI 
/* 
  - KOMPILASI ATAU MENGUBAH SOURCE CODE MENJADI BINARY CODE, 
  - MEM-PACKAGE BINARY CODE MENJADI DISTRIBUTION FILE, 
  - MEMBUAT DOKUMENTASI 
  - MENJALANKAN AUTOMATED TEST
  - MANAJEMEN ATAU MENGATUR DEPEDANCY
*/
//! 1. APA ITU GRADLE 
